### PR TITLE
Added virStorageVolCreateFlag

### PR DESCRIPTION
**Pull request by slaykovsky**
Added VIR_STORAGE_VOL_CREATE_REFLINK as it was not here.

### CODE REVIEW

**Comment by rmohr** [comment]
Hi @slaykovsky,

Thanks for the contribution. Could you add the constant in a new file called constants_1.2.14.go ? The flag is not available in 1.2.2.

**Comment by slaykovsky** [comment]
Hello @rmohr !

Yes, will do today :)

**Comment by slaykovsky** [comment]
Hi @rmohr,

Added a new file as you said.

**Comment by rmohr** [comment]
@slaykovsky thx

**Pull request merged**
