### PR TITLE
Add VirDomainBlockStat

### PR DESCRIPTION
**Pull request by feiskyer**
Add VirDomainBlockStat to libvirt-go

### CODE REVIEW

**Comment by feiskyer** [comment]
@rgbkrk Any updates on this?

**Comment by rgbkrk** [comment]
Let's take it and try it out. Adding you on to help maintain and collaborate.

**Comment by feiskyer** [comment]
Thanks.

**Comment by feiskyer** [comment]
@rgbkrk Could you add a CI integration for safely checking new PRs?

**Comment by rgbkrk** [comment]
Sure, seems like we need to find a good place to do it. Running locally now.

**Comment by feiskyer** [comment]
Try https://travis-ci.org ?

**Comment by rgbkrk** [comment]
That's what I use on everything else, wasn't sure if we'd have enough flexibility there. Happily enabled anyway.

**Comment by alexzorin** [comment]
My 2c: I think there were maybe running on travis because of how Docker and libvirt interact, which is why the tests run in vagrant/virtualbox. Might have something to do with privileged containers? Suggest validating these vague memories one way or another, though.

**Comment by rgbkrk** [comment]
That definitely makes sense. Ran the tests locally by the way, using the vagrant set up. Enabled drone.io as well, happy to run that on carina as well if we want to run our own base image.

**Comment by feiskyer** [comment]
There is a `TRUSTY BETA` VM based environment on travis: https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments.

It should be OK to run tests.

**Pull request merged**
