### PR TITLE
Add IsPersistent() for domains

### PR DESCRIPTION
**Pull request by nseps**
* Same logic as IsActive()
* buildTransientTestDomain() added to domain_test

### CODE REVIEW

**Comment by nseps** [comment]
My libvirt-dev is 1.3.1 btw. I haven't check if virDomainIsPersistent() is available at 1.2.2.

**Comment by feiskyer** [comment]
It worked on v1.2.17

**Comment by nseps** [comment]
@feiskyer so are we good to merge?

**Comment by feiskyer** [comment]
lgtm

**Pull request merged**
