### PR TITLE
Add virDomainLookupByUUIDString (already available in 1.2.2)

### PR DESCRIPTION
**Pull request by dmacvicar**

### CODE REVIEW

**Comment by rgbkrk** [comment]
Test + code :white_check_mark: 

I'd rather not introduce more public functions at the moment, especially as we gear toward Go 1.6. Will you be available to support this in the future?

**Comment by rgbkrk** [comment]
Also, my apologies for letting this sit. Thank you for the contribution.

**Comment by dmacvicar** [comment]
Thanks for the review.

I am just upstreaming everything I needed for https://github.com/dmacvicar/terraform-provider-libvirt and I will certainly need to add more functions to my fork e.g. `virDomainInterfaceAddresses` on order to get the ip address of the domain in terraform.

It would be interesting to know if I should take the effort in upstreaming those. I have no problem to keep them in my fork.

**Comment by rgbkrk** [comment]
Thanks @dmacvicar.

**Pull request merged**
