### PR TITLE
Added VirDomainBlockStat and header file for c

### PR DESCRIPTION
**Pull request by sandlbn**

### CODE REVIEW

**Comment by alexzorin** [comment]
Could you elaborate on what the fix is in bb05a87 ?

**Comment by feiskyer** [comment]
What's the status of this PR?

**Comment by alexzorin** [comment]
See deprecation notice in README

**Comment by feiskyer** [comment]
So you will not updating this repo in future?

**Comment by rgbkrk** [comment]
Since there are no responses from the original submitter, closing. Feel free to open if you're looking to add this in.

**Pull request closed without merging**
