### PR TITLE
Add VirDomainMigrateToURI

### PR DESCRIPTION
**Pull request by asaif**

### CODE REVIEW

**Comment by asaif** [comment]
created pull request for the wrong branch .. will open another one

**Comment by alexzorin** [comment]
Looks like you've added one or more constants that are not present in libvirt 1.2.2 and so the build is failing.

As per README could you adjust the PR to successfully compile against libvirt 1.2.2?

**Comment by asaif** [comment]
Remove the constant not available on 1.2.2

**Comment by rgbkrk** [comment]
This needs a rebase to press forward with, though it seems like I'm going to need to set up Drone.io for this project in the same way Alex did.

**Comment by hinesmr** [comment]
@alexzorin I wrote the `VIR_MIGRATE_RDMA_PIN_ALL` constant :) ...... is there a way to conditionalize the constant so that it's not dropped for everyone?

**Comment by hinesmr** [comment]
@alexzorin Also, please write at least one test for the migration by performing a localhost-only migration. Refer to libvirt-go/domain_test.go function `buildTestQEMUDomain` for an example of how to test this with QEMU, unless you have another type of hypervisor you want to test it with.

**Comment by rgbkrk** [comment]
I'm going to go ahead and close all PRs that have been open for more than 6 months, including this one. If it needs reopened feel free to do so or open a new PR.

**Pull request closed without merging**
